sudo: false
language: node_js
node_js:
  - '12'

script:
  - npm test

deploy:
  provider: script
  script: sls deploy
  skip_cleanup: true
  on:
    repo: photon-sdk/photon-keyserver
    branch: deploy/photonsdk-dev
